mongock:
  change-logs-scan-package:
    - com.github.cloudyrock.mongock.integrationtests.spring5.springdata3.changelogs.client
  trackIgnored: true
  transactionable: false

  #    - com.github.cloudyrock.mongock.integrationtests.spring5.springdata3.changelogs.client.initializer2
  #    - com.github.cloudyrock.mongock.integrationtests.spring5.springdata3.changelogs.client.updater
  #    - com.github.cloudyrock.mongock.integrationtests.spring5.springdata3.changelogs.client.ClientUpdater2ChangeLog
